CREATE TABLE IF NOT EXISTS `brand_report` (
  `no_urut` int(11) NOT NULL AUTO_INCREMENT,
  `nm_brand` varchar(100) NOT NULL,
  PRIMARY KEY (`no_urut`),
  UNIQUE KEY `uq_nm_brand` (`nm_brand`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `brand_report` (`nm_brand`) VALUES
('BC OMG'),
('OMG'),
('EMINA'),
('WARDAH'),
('MAKE OVER'),
('KAHF'),
('SKINTIFIC MARINA'),
('G2G'),
('GLAD2GLOW'),
('HANASUI'),
('SLAVINA'),
('SCARLET'),
('HADALABO'),
('IMPLORA'),
('VIVA'),
('GLOW & LOVELY'),
('PONDS'),
('GARNIER'),
('CUSSONS'),
('NIVEA'),
('PIXY'),
('MAKARIZO'),
('YOU'),
('NYU'),
('MIRANDA'),
('DAZZLE ME'),
('ANIMATE'),
('MY BABY'),
('MOELL'),
('NPURE'),
('SCORA'),
('FACETOLOGY'),
('JHONSONS'),
('EUREKA'),
('EVANGELINE'),
('VITALIS'),
('GATSBY'),
('PUCELLE'),
('ANDO'),
('PRO ATT'),
('CARVIL'),
('BENING'),
('LOGO'),
('NEW ERA'),
('SPEED'),
('ARMOD'),
('LUBRENA'),
('VAUSTIN');
